name: 🐛 Bug Report
title: '[BUG REPORT] Bug'
description: A bug in the icon or elsewhere
labels: 'bug report'
body:

- type: input
  id: bug
  attributes:
    label: The bug
    description: "A complete of what the bug is"
  validations:
    required: true
    
- type: input
  id: steps
  attributes:
    label: Steps to reproduce
    description: "What'd you do to make the bug happen?"
    placeholder: "1. Load the file into The Dude v7.16.2... 2. When selecting the icon it looks bad..."
  validations:
    required: false

- type: dropdown
  id: dudeversion
  attributes:
    label: What is your version of Mikrotik The Dude?
    options:
      - RouterOS v7.x
      - RouterOS v6.x
      - CHR v7.x
      - CHR v6.x
      - v4.0beta3
      - v3.6
  validations:
    required: true
    
- type: input
  id: extra
  attributes:
    label: Any extra info
  validations:
    required: false
