name: 💡 Feature Request
title: '[FEATURE REQUEST] Feature'
description: Request a feature
labels: 'feature request'
body:

# skill name block
- type: input
  id: request
  attributes:
    label: Feature requested
    description: "The feature you're requesting."
    placeholder: "Add this endpoint because..."
  validations:
    required: true
